### ISSUE TITLE
File from previously closed Folder stays open in a split screen

### ISSUE THREAD

**Issue by quiquejbb** [mikailcolak/brackets-color-picker#1]
The issue is that when one has a Folder open with an html file on view, and then decides to Open a different Folder, the html from the first opened folder stays in the main view (alongside the new html) and sticks as if it were a horizontal split (even though a split wasn't even active before). It is not possible to close this, unless one quits Brackets or plays around with the file tree and folders.
Steps:
*I Open a folder and click on a file so as to make it a working file (e.g. a test1.html). I then click the folder dropdown and select another Folder (test2). First problem is that the Test2 Folder does not open immediately, I have to repeat the process so the actual test2 Folder opens. After this is done, in most cases it will open the test2.html and have a split screen on the top with partial text from the previous test1.html file that I was viewing. 

![image](https://cloud.githubusercontent.com/assets/8852154/4560667/c02258e4-4ef6-11e4-9139-6e12fdf9a9d4.png)

I have several extensions, but tried every single one of them individually and it seems that Color-Picker was the issue.

The extensions I have are

![image](https://cloud.githubusercontent.com/assets/8852154/4560694/e8f0b784-4ef6-11e4-89af-62c30356ad2f.png)

**Comment by mikailcolak** [comment]
First thank you for report me to this problem, i'm going to investigate this and fix the problem.

**Comment by quiquejbb** [comment]
Thank you! Btw I forgot to mention its the latest brackets on win 8.1.

**Comment by mikailcolak** [comment]
hmm thank you again i'm going the find a solution with given informations from you :).

**Comment by mikailcolak** [comment]
I think problem was gone, but maybe appear some another issues, i'm not capable the know right now because i'm little busy, if you or somebody found another issue, please let me know. Thank you.
